### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Nathan187** [nunit/nunit.xamarin#103]
How about updating the documentation for Visual Studio for Mac?

**Comment by ChrisMaddock** [comment]
Are you referring to the documentation at the link below?

https://github.com/nunit/docs/wiki/Getting-Started-in-Visual-Studio-for-Mac

This was written by a contributor - I don't believe we have anyone who regularly uses VS for Mac. What's outdated? If you're able to propose an updated version, we'd love to have it - I've copied the markdown for the guide to the link below, so you can access it. 

https://gist.github.com/ChrisMaddock/8a1d1d096c13454df46b6e9112bc3f5d
