### ISSUE TITLE
Unable to compile android app with this nunit xamarin runner referenced

### ISSUE THREAD

**Issue by Danny138** [nunit/nunit.xamarin#120]
I am new to the Android App development with Xamarin. After creating a C# Android App in the Visual Studio and referencing the nuget package of this nunit xamarin runner, I have a hard time to get the project compiled and run. Is there tutorial or examples for beginners?

**Comment by ChrisMaddock** [comment]
Try the docs here: https://github.com/nunit/docs/wiki/Getting-Started-in-Visual-Studio

There’s a separate guide linked in the sidebar if you’re using VS for Mac. 😊

**Comment by ChrisMaddock** [comment]
Closing this, as I think the questions answered. Feel free to comment further if not, the team will still get the notifications. 🙂
