### ISSUE TITLE
Whoa, did I just see a stable release?

### ISSUE THREAD

**Issue by tofutim** [nunit/nunit.xamarin#32]
I went to nuget and saw it. :)

**Comment by tofutim** [comment]
Uh oh UWP not included? I see that the PCL NUnit.Runners get installed but I cannot get to the NUnit.Runner namespace in using.

**Comment by tofutim** [comment]
Maybe it isn't really ready. I tried both UWP and Droid and nothing comes out of the nuget.

**Comment by rprouse** [comment]
@tofutim, preparing a release now. It will be `nunit.xamarin` on Nuget. Should be out within the hour.

**Comment by rprouse** [comment]
@tofutim, want to be the first to try the release? The NuGet is available at https://www.nuget.org/packages/nunit.xamarin

Read through the README at https://github.com/nunit/nunit.xamarin for instructions.

Please let me know how it goes and if you have any problems. :+1:

**Comment by tofutim** [comment]
I'll try it again.

**Comment by tofutim** [comment]
Same problem as before - I see NUnit.Runners in the references - but 

Severity	Code	Description	Project	File	Line
Error	CS0234	The type or namespace name 'Runner' does not exist in the namespace 'NUnit' (are you missing an assembly reference?)	SQLite.Net.Tests.UWP	D:\Loqu8\Projects\sqlite-net\tests\SQLite.Net.Tests.UWP\MainPage.xaml.cs	32

**Comment by tofutim** [comment]
![image](https://cloud.githubusercontent.com/assets/157766/11230863/ee564fcc-8d57-11e5-860d-9f2e863a1797.png)
Not sure you can see it there, but when I press . after NUnit it gives me Common and Framework, but no Runners, even though you see in the solution (for UWP) that it NUnit.Runners is there.

**Comment by tofutim** [comment]
Something is wrong with the package, it is not opening!

![image](https://cloud.githubusercontent.com/assets/157766/11230913/55fa6a28-8d58-11e5-9018-deeb5fc6ff26.png)

**Comment by CharliePoole** [comment]
Tim, you seem to be using the updated NUnit.Runners package, which has
nothing to do with Xamarin! It contains the NUnit console runner as a tool
and doesn't have anything for you to reference.

When Rob releases the Xamarin runner package, he will announce it.

Charlie
