### ISSUE TITLE
Could not copy the file "...nunit.xamarin\src\runner\nunit.runner.uwp\bin\Debug\nunit.runner.uwp\Properties\nunit.runner.uwp.rd.xml" because it was not found.	

### ISSUE THREAD

**Issue by tofutim** [nunit/nunit.xamarin#34]
Not sure why, when I try to include the uwp.dll from another directory and try to build, I get this odd error:

Severity	Code	Description	Project	File	Line
Error		Could not copy the file "D:\Loqu8\Projects\nunit.xamarin\src\runner\nunit.runner.uwp\bin\Debug\nunit.runner.uwp\Properties\nunit.runner.uwp.rd.xml" because it was not found.	SQLite.Net.Tests.UWP		

No rd.xml file in the output;

![image](https://cloud.githubusercontent.com/assets/157766/11231047/a1c3b044-8d59-11e5-97ac-cdcaa6889030.png)

Update: It is a runtime directive file (rd.xml) - http://metronuggets.com/2015/07/30/my-uwp-nuget-package-is-missing-a-file/

**Comment by tofutim** [comment]
We need to "Generate Library Layout" like https://github.com/MvvmCross/MvvmCross/pull/1109

**Comment by tofutim** [comment]
![image](https://cloud.githubusercontent.com/assets/157766/11231241/59176c94-8d5b-11e5-9009-85d6d4e86c64.png)

**Comment by rprouse** [comment]
I will take a look and add it if required. Odd though, I've managed to create and run Windows 10 test runners using the package. :question:

**Comment by tofutim** [comment]
Not sure, but it didn't work on my end. The runners do work from the solution though. I think you need to create the rd.xml and included it in the nuget.

**Comment by tofutim** [comment]
Incidentally, the package did not work for me, this is from manually referencing your sln output from mine. The package did not work for me, I get a blank nuget folder.

**Comment by tofutim** [comment]
See my notes https://github.com/nunit/nunit.xamarin/issues/32

**Comment by rprouse** [comment]
I am pretty sure you are using the wrong NuGet package. I think you are using `nunit.runner`, that only installs the console and will be an empty package. The NuGet package you want is `nunit.xamarin`

**Comment by tofutim** [comment]
I think you are right. I'll try that.

**Comment by tofutim** [comment]
I'm embarrassed, that sure solved my problems. No need for the rd.xml. Sorry for the distractions.
