### ISSUE TITLE
unable to run async tests in UWP

### ISSUE THREAD

**Issue by tofutim** [nunit/nunit.xamarin#38]
Is this a UWP, nunit, nunit.runners issue? I added this to the tests in this solution after seeing it in mine.

        [Test]
        public async Task AsyncTest()
        {
            var result = await anInt();
            Assert.AreEqual(42, result);
        }

        private async Task<int> anInt()
        {
            return 42;
        }

![image](https://cloud.githubusercontent.com/assets/157766/11246511/cef21880-8dcc-11e5-88cf-613c49124dc2.png)

**Comment by rprouse** [comment]
Why did you close this? Did you get it working? If so, what did you need to do? Add BCL?
