### ISSUE TITLE
nuspec setup

### ISSUE THREAD

**Issue by tofutim** [nunit/nunit.xamarin#39]
Hi I was wondering how you usually run the nuspec, I was trying to test to build it but it didn't work because it thinks that there is an extra nuget/ folder. I ran it from both the nuget and main directory.

![image](https://cloud.githubusercontent.com/assets/157766/11247127/99d2368c-8dcf-11e5-98cf-4ba99eb1fc1e.png)

**Comment by tofutim** [comment]
Looks like I needed -BasePath . from the command line.

**Comment by tofutim** [comment]
Also the nuget asks for         
<file src="nuget\uap10.0\MainPage.xaml.cs.txt.pp" target="content\uap10.0\MainPage.xaml.cs.txt.pp" />
did you mean to use the same as the wp81 one?

**Comment by rprouse** [comment]
I build and package using the Cake build script on the command line. Use the command `build.ps1 -Target package`

Other targets are clean and build. Read through build.cake for more info.

**Comment by rprouse** [comment]
The mainpage for UWP is slightly different than the win81 version. It also looks like you are working on a branch based off an older version of master. You need to get latest from master. The nuspec you are working with is pre-release, it now looks like https://github.com/nunit/nunit.xamarin/blob/master/nuget/nunit.runners.xamarin.nuspec
