### ISSUE TITLE
Update the README for 3.2

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit.xamarin#53]

**Comment by ChrisMaddock** [comment]
Includes:

- Remove WP8.1 metnions
- TCP Writer option
- Create XML file/specify path options
(+ document all other available options.)

@rprouse - The Readme's getting pretty long, and adding another table of options will only make it longer. Any objection if I move the bulk to docs?

Just tidying up the minor issues for 3.2 at the moment, so hopefully we'll just need to decide where to go with the agent, and then things will be ready to go. 😄

**Comment by rprouse** [comment]
I agree that much of this should be moved to docs.
