### ISSUE TITLE
Asserts counter displays wrong number

### ISSUE THREAD

**Issue by har07** [nunit/nunit.xamarin#55]
Actually I'm not sure if this is really a bug since I'm new to NUnit, and if it is, on which project repository should I post it...

Anyway, it was displayed that `Asserts: 0` when I run my NUnit Android Test Runner, despite in the corresponding test method `Assert.True()` are called in two different places, and I can confirm it is executed since breakpoints on those two places are hit as expected.

[![enter image description here][1]][1]

I posted [the same problem on StackOverflow](http://stackoverflow.com/questions/37237114/why-asserts-equals-0-zero-in-nunit-android-test-runner) yesterday, and suggested the problem might be because asserts are called after async method-call in my case. It looks like to me that the suggestion is correct, since the following simple test which contains a call to async method successfully reproduce the problem (asserts count displays `0` while it should be `1`): 

    [Test]
    public async Task TestAsyncCounter()
    {
    	await FakeAsyncMethod();
    	Assert.True(true);
    }
    
    public async Task FakeAsyncMethod()
    {
    	await Task.Delay(1000);
    }

Might as well take this chance to thank you guys for the awesome library! :+1: 

  [1]: http://i.stack.imgur.com/bYXRy.png

**Comment by CharliePoole** [comment]
We should test this out on the desktop as well, if we don't already have similar tests. It could easily be a framework issue rather than specific to the Android runner.

**Comment by CharliePoole** [comment]
I created a branch in the nunit repo with some tests. There doesn't seem to be a problem on the desktop, including using the portable framework build. See the branch assert-counts. I want to add a few more tests and I'll add them to the SL and CF builds when I have access to a Windows machine. However, it looks like this issue is in the right place.

**Comment by CharliePoole** [comment]
OK, I have to take back that last comment. It works correctly when the awaited method doesn't contain an await itself and is therefore processed synchronously. I'm seeing odd results when I include `await Task.Delay(1)` in the awaited method. So there is definitely a framework bug and it can even be seen in .NET 4.5.

**Comment by ChrisMaddock** [comment]
This issue looks to be with the framework, and is logged as https://github.com/nunit/nunit/issues/1499.

Am closing this as I don't think there's any change that needs to be made in this repo, please undo if I'm wrong!
