### ISSUE TITLE
How do i get the result out from CreateXmlResultFile on iOS ?

### ISSUE THREAD

**Issue by donnib** [nunit/nunit.xamarin#58]
Hi,
If i run some tests and the runner on iOS produces an NUnit xml output how do i get the file from the ios device programatically ?

/donnib

**Comment by rprouse** [comment]
First, the create XML results haven't been released yet. Hopefully soon :smile: 

Second, I don't know :confused: 

Sorry, I don't do a lot of iOS development, I mainly concentrate on Android. It is a good question, so I will leave it open to the community. Hopefully someone can provide suggestions and we can document it.

**Comment by ChrisMaddock** [comment]
@donnib - @epsmae has just finished adding a `ResultFilePath` option to allow specifying a filepath when constructing the test options - see PR #60. It'll be in v3.2, or of course you can build from master to get it earlier!
