### ISSUE TITLE
Enable adding multiple assemblies to test

### ISSUE THREAD

**Issue by jamesmundy** [nunit/nunit.xamarin#59]
Currently trying to use this for in Android. I have the Android test app with one test in and a shared portable library with one test in. When I try to add the extra assembly like (nunit.AddTestAssembly(typeof(TestInOtherAssembly).Assembly); ) the test in my original assembly is not run.

If add both the original and portable assembly only the assembly I add last is run.

nunit.AddTestAssembly(typeof(TestInOtherAssembly).Assembly);
nunit.AddTestAssembly(typeof(TestInOriginalAssembly).Assembly);

Any ideas?

**Comment by rprouse** [comment]
Could be a bug, I will need to check the code.

**Comment by ChrisMaddock** [comment]
I think I've just hit the same problem poking around at #48. It looks like the code loads all the assemblies into `NUnitTestAssemblyRunner` before running any, but `NUnitTestAssemblyRunner` only holds/runs a single assembly.

@rprouse - architecturally, where should responsibility for combining test results lie? I was looking at integrating this with the portable agent, which (from a quick look!) also only loads/runs single assemblies. Is it the responsibility of the runner to combine results from multiple assemblies, or should that live in the framework/agent? It sounds like it would be useful at agent level, save it being duplicated in all runners?

**Comment by rprouse** [comment]
@ChrisMaddock I was also thinking of using the portable agent in the Xamarin runners. When I originally wrote the Xamarin runner, I was duplicating too much code, so when I wrote the portable agent, I kept that in mind and moved as much as I could into it. Based on that, i think that the responsibility for running and combining results from multiple assemblies should be in the portable agent, then we get the fix in every runner that will eventually use it.

**Comment by ChrisMaddock** [comment]
@rprouse - Great, thanks. I think that is pre-requisite to #48, which would also fix this bug. I may have an attempt at it. 😄

**Comment by rprouse** [comment]
@ChrisMaddock it is all yours. I've changed the assignment 😄

**Comment by ChrisMaddock** [comment]
@rprouse - Sorry, I meant I'll attempt adding multi-assembly runs to the agent, to fix #48! Although that should fix this by default - no intention to steal the issue from you! 😆

**Comment by ChrisMaddock** [comment]
Blocked by https://github.com/nunit/nunit.portable.agent/issues/13 and then #48. I think we could work around it if needed, but it would be a short-term fix.

**Comment by ChrisMaddock** [comment]
#48 has been removed from the milestone, this should instead be fixed independently.
