### ISSUE TITLE
Update library versions

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit.xamarin#65]
As discussed on https://github.com/nunit/nunit-vs-templates/issues/22

Xamarin and UWP definitely want updating, I haven't looked in to equivalent issues on other platforms. This should be done in sync with the issue above. 

With UWP I believe it would be good if we could keep the current min version, and target latest - we'd possibly need to look in to running CI against the min version to ensure compatibility.

@rprouse - I've created a few issues to cover our conversations in various places over the last few days - and I'm bundling them all into 3.2. Hope you don't mind - please feel free to undo this if you had other plans!

**Comment by rprouse** [comment]
@ChrisMaddock your issues look good. Thanks for putting so much work in this. I want to move the .NET Core runner and framework forward, so this takes some of the pressure off.
