### ISSUE TITLE
Make the Icon Larger

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit.xamarin#70]
@rprouse commented on [Wed Nov 16 2016](https://github.com/nunit/nunit3-vs-adapter/issues/268)

I think it is because we are using the recommended icon size from the v1 VSIX format, but our icon on the new Visual Studio Marketplace is much smaller than most other extensions. Minor from a code perspective, but I think important from a professionalism perspective.

https://marketplace.visualstudio.com/items?itemName=NUnitDevelopers.NUnit3TestAdapter

![image](https://cloud.githubusercontent.com/assets/493828/20329498/9d847dc0-ab66-11e6-9b13-a652cca8ff25.png)

![image](https://cloud.githubusercontent.com/assets/493828/20329509/ad65a304-ab66-11e6-8b7e-9159500d4b4c.png)

---

@CharliePoole commented on [Wed Nov 16 2016](https://github.com/nunit/nunit3-vs-adapter/issues/268#issuecomment-260855832)

We may need to keep this in multiple sizes.

---

@ChrisMaddock commented on [Wed Nov 16 2016](https://github.com/nunit/nunit3-vs-adapter/issues/268#issuecomment-260956111)

We actually have the same issue on NuGet gallery (for _almost_ all packages), and of course for all the other extensions. 

New icons for everyone! 😄 

---

@rprouse commented on [Wed Nov 16 2016](https://github.com/nunit/nunit3-vs-adapter/issues/268#issuecomment-260959772)

> We may need to keep this in multiple sizes.

True, we will need to go back to VS 2012 and ensure whatever we use there continues to work. The screenshot above is for the 2012 version of Web Essentials, so I expect the larger icons are fine there too. The small icons are probably a hold back to the VSIX v1 format.

---

@CharliePoole commented on [Wed Nov 16 2016](https://github.com/nunit/nunit3-vs-adapter/issues/268#issuecomment-260974768)

What are we using for file explorer with the console?

---

@rprouse commented on [Wed Nov 16 2016](https://github.com/nunit/nunit3-vs-adapter/issues/268#issuecomment-260975802)

The console uses an ICO with large size icons embedded in it. I think the NuGet and VSIX require large PNG files, but I need to check.

---

@rprouse commented on [Fri Nov 25 2016](https://github.com/nunit/nunit3-vs-adapter/issues/268#issuecomment-262965742)

I downloaded several popular extensions that look good in Visual Studio and in the marketplace to check their icon sizes. A couple were 64x64, WebEssentials was 90x90 and one was 250x250.

---

@ChrisMaddock commented on [Fri Nov 25 2016](https://github.com/nunit/nunit3-vs-adapter/issues/268#issuecomment-262966419)

For NuGet - the biggest 'displayed' icon is 128x128 in the gallery, the recommendation seemed to be 256x256, for high dpi screens. There's open requests for ico/multiple file size support, nothing implemented yet however.

**Comment by CharliePoole** [comment]
I'm wondering if this discussion about icons and sizes should be somewhere more general. Don't we want to use the same set of icons for every application?

**Comment by ChrisMaddock** [comment]
@CharliePoole - Definitely! Sorry - I just copied this issue over here as I wanted to make sure it didn't get forgotten for the next release.

I think this should be done for all our VSIXs/NuGet packages, we just need to decide on the sizes. Where do you want to have that conversation? 😄

**Comment by CharliePoole** [comment]
Where do we want the icons to live? I would create the issue in that project and either make it an epic or just do a manual task list inside the issue to update each package that needs to use them.

IIRC some of our resources currently live on nunit.org while others live in github.

**Comment by ChrisMaddock** [comment]
That sounds like a discussion in itself! @rprouse spotted it first and created https://github.com/nunit/nunit3-vs-adapter/issues/268 - let's use that as the master issue. I'll add a list of everywhere to update!

**Comment by rprouse** [comment]
> I'm wondering if this discussion about icons and sizes should be somewhere more general. Don't we want to use the same set of icons for every application?

@CharliePoole We use the same icon, but in different formats and sizes depending on the use. The VSIX uses a PNG as the icon with one size. I tried an ICO, but I don't think it works properly on the web. Every VSIX I checked used PNGs.

Any of our executables use the ICO version. It has all sizes correctly embedded in it and does not need to be changes.

I haven't looked at the icon for NuGet packages yet and didn't even know they were an issue until @ChrisMaddock  pointed it out. Ours are definately smaller on NuGet.org. It looks like the larger ones are pulling from `Content/Images/packageDefaultIcon-50x50.png`

**Comment by CharliePoole** [comment]
@rprouse Yes, I understood that. But it would be handy if we kept them all in the same place, using different names at least insofar as they are accessed via a url. Of course, some of them get bundled into the package and have to be copied, but it would be nice to know for sure where to look for the right icon when one is needed.

**Comment by rprouse** [comment]
@CharliePoole I suggested in the other issue that we store collateral in the docs repo. It is sitting there with nothing but a readme. Sound good?

**Comment by CharliePoole** [comment]
See my comment there... but docs would be OK with me as well. 

Originally, I didn't want to "waste" a separate repo on stuff like this, but they are free. :-)
