### ISSUE TITLE
Is possible to run Nunit.Xamarin on a CI and get the results?

### ISSUE THREAD

**Issue by GiusepeCasagrande** [nunit/nunit.xamarin#81]
The title say almost all of it :)

We are trying to setup a CI/CD with VSTS + Hockey App, right now I have two sets of tests that I need to run there that dependes on Test Harness.

From what I could see xUnit supports it like this: http://jj09.net/continuous-integration-and-continuous-delivery-for-xamarin-ios-with-vsts/

I tried to use it a reference and implement  on Unit but no success so far.

Any direction, link or tips would be welcome.

**Comment by rprouse** [comment]
@GiusepeCasagrande what I do is make my unit tests a shared project that is referenced from .NET 4.5, iOS and Android test projects. Any platform specific tests are defined out with an `#if`. I find that the majority of our tests will run in .NET 4.5, so I can run them in Visual Studio as I develop and in VSTS for continuous integration. For the few platform specific tests, we run them manually.

This only works if the majority of your business logic is in a PCL, not a shared project. Reading the article you linked to, I am pretty certain that they are doing the same thing. AFAIK, xUnit Console is not capable of running Xamarin Android or iOS.

For a walkthrough on how I setup the projects, see http://www.alteridem.net/2015/12/21/testing-xamarin-projects-using-nunit-3/

**Comment by plneto** [comment]
@GiusepeCasagrande  I finally managed to run my tests on an iOS test harness project in VSTS using https://github.com/ghuntley/Cake.AppleSimulator along with the changes from this PR #83  

I'm using a Cake task to grab the test results .xml from the iOS simulator folder so I can upload it but I get the following error 

`Failed to publish test results: Invalid file format.`

It looks like VSTS only accepts NUnit 2 format 👎

**Comment by GiusepeCasagrande** [comment]
@rprouse Thanks for the answer, I'll use you post as reference.
@plneto I guess I saw your discussion with @ghuntley at some place, and I'll take a look into it as well. Let me share with you another two links that I have on my sleeve: 
https://github.com/ghuntley/Cake.AppleSimulator/pull/4?utm_campaign=Weekly%2BXamarin&utm_medium=web&utm_source=Weekly_Xamarin_116#issuecomment-266957347 ( I guess this one isn't new to you)

And http://kent-boogaart.com/blog/using-the-visual-studio-test-runner-for-mobile-development

Right now I had to drop the task to make it run on VSTS to invest my time on other things, but I guess that next week I'll be back on it and I can repot my finds here.

**Comment by ChrisMaddock** [comment]
> Failed to publish test results: Invalid file format.
> It looks like VSTS only accepts NUnit 2 format

@plneto - VSTS started accepting NUnit 3 results relatively recently - although I'm afraid I don't know which VSTS release it went out in to, and whether it's live yet or not. :-/ The TestResult.xml produced by the current master isn't actually entirely valid though, unfortunately. That should be fixed in #82 - do you want to try pulling that in, and see if it works? If not - can you share the xml and we can check?

This is really cool stuff, I haven't looked before at integrating a platform-specific runner in CI. Can I ask (purely out of interest!) what #83 is necessary for - are you waiting on app close to shutdown the simulator? Is there any chance you could give us a quick run through of the process? Would be great to add a quick summary to the docs!

**Comment by ChrisMaddock** [comment]
@plneto 
Here's the VSTS PR, looks like its not released yet. :-(
https://github.com/Microsoft/vsts-agent/pull/629

**Comment by plneto** [comment]
> Edit: Whoops - just seen #84! So am I right, the process looks a little like this?
> 
> 1.     Fire up apple sim
> 2.     AutoRun tests
> 3.     Shutdown app (required step for Cake plugin to shutdown sim cleanly?)
> 4.     Shutdown sim
> 5.     Retrieve test result xml

@ChrisMaddock Yes, that's exactly right. #83 would be required to perform step 3 otherwise the Cake plugin fails to shutdown the simulator and returns an error.

I didn't know the current result .xml wasn't valid. I'll try both #82 and the JUnit approach and I'll post the results here later.

**Comment by plneto** [comment]
After merging #82 (branch issue-59) the test results were uploaded successfully using the NUnit format. 

Thanks @ChrisMaddock 👍 Looking forward to the next release.

![image](https://cloud.githubusercontent.com/assets/5697434/21949279/905ed71c-da3c-11e6-9801-badc4596fb6a.png)

**Comment by ChrisMaddock** [comment]
Woohoo! 🎉

Just to check - are all those zero second duration's expected, or is something broke somewhere? Is it something I've missed setting in the xml, or is VSTS just not reading it right?

**Comment by plneto** [comment]
The total duration seems to be populating the seconds correctly but it's ignoring the milliseconds.
It was 0:00:08.212 but it shows only 0:00:08.000

The individual tests are always showing 0s.

I ran the build once with all the sample test cases from this repository, and I also added 2 tests with a pause to test the duration (test_duration - 3 seconds, failed_test_duration - 5 seconds).

Below are the results. Do you think it's something wrong with how VSTS is reading the results?

![vsts](https://cloud.githubusercontent.com/assets/5697434/21966616/630f166e-dbc2-11e6-833b-2c803060241c.png)

[UnitTestsResults.xml.zip](https://github.com/nunit/nunit.xamarin/files/706940/UnitTestsResults.xml.zip)

**Comment by ChrisMaddock** [comment]
It looks like VSTS is deducing duration as `end-time` minus `start-time`, which would only have second accuracy, rather than utilising the `duration` attribute, which gives millisecond precision. The NUnit xml looks accurate

Might be worth a bug report to those guys? Like I say - I'm not sure if the NUnit 3 support from VSTS has actually been released yet - it could be that it's instead reading the result file as if it were NUnit 2 - and falling back to a calculated duration when it can't find NUnit 2's `time` attribute.

**Comment by plneto** [comment]
I was using vsts-agent 2.110.0 which already included the NUnit 3 results PR. I also tried the latest vsts-agent pre-release v2.111.1 but the same thing happens.

I'll report the issue to them. Thanks for your help.

**Comment by ChrisMaddock** [comment]
Great, thanks!

**Comment by ChrisMaddock** [comment]
I'm going to close this as needing no further action - @GiusepeCasagrande - let us know how you get one, though. 👍

**Comment by GiusepeCasagrande** [comment]
Sure @ChrisMaddock, I may get back to it in this week. I'll report back my results. 
But thank you all for all the tips and support so far.
