### ISSUE TITLE
Allow app to be terminated automatically after running the tests

### ISSUE THREAD

**Issue by plneto** [nunit/nunit.xamarin#84]
I think it would be useful to allow the app to be terminated automatically. When using https://github.com/ghuntley/Cake.AppleSimulator to run the tests on a simulator as part of a CI build, the app must be terminated for the build to complete.

I've created a PR #83 and a temporary nuget package with this change so I could use it in one of my projects and it seems to be working fine. Here's the link if anyone wants to test it https://www.nuget.org/packages/nunit.xamarin.plneto

**Comment by rprouse** [comment]
This is an excellent idea. As I said, we will look at the PR as soon as we can.
