### ISSUE TITLE
Nunit.Runner.App doesn't have the property 'Options'

### ISSUE THREAD

**Issue by joaoasilva** [nunit/nunit.xamarin#92]
Hi,

I'm trying to generate an XML from my tests for CI using jenkins on a Mac with a Xamarin.Forms App.
By following this: https://github.com/nunit/docs/wiki/Getting-Started-in-Visual-Studio-for-Mac, I've added my tests, they run fine on an Android Simulator but for some reason when I try to setup my NUnit.Runner.App.Options they aren't available as per:
https://github.com/nunit/docs/wiki/NUnit-Xamarin-Runners
Am I missing something?

I only have the property NUnit.Runner.App.AutoRun available, even this one should be located inside NUnit.Runner.App.Options.AutoRun, right?

Thanks.

**Comment by plneto** [comment]
I think the latest version available on nuget doesn't have Options yet. 

You can try this https://www.nuget.org/packages/nunit.xamarin.plneto/ which contains more recent changes, including Options. 

This is an unofficial package and it will be removed once the official one has been updated.

**Comment by ChrisMaddock** [comment]
@plneto's correct. Sorry, we were aiming to release nunit.xamarin 3.6 last month, but unfortunately life got in the way. The doc's were updated ready for this, but the release itself never quite got finished.

The latest version on NuGet is 3.01, which as you've spotted, only has the AutoRun option. If you're after the test XML however, I think you'll need a more recent build - as the file xml was added after v3.01. You can find a NuGet package of out latest build of master from our CI feed: https://ci.appveyor.com/nuget/nunit.xamarin

One of the last steps we needed to do for the 3.6 release was to check everything still works in the iOS build - particularly that it works with the new version of NUnit (3.6). @plneto - iirc you do a bit of iOS stuff? Unfortunately I don't have access to a mac to test on at the moment, any chance you'd be able to check the NuGet package in PR #85 ([link](https://ci.appveyor.com/project/CharliePoole/nunit-xamarin/build/3.0.1-ci-00132-update-libr/artifacts)), and make sure everything still works as expected on iOS? If we can get that sorted, we can hopefully get the next release moving.

**Comment by plneto** [comment]
@ChrisMaddock I just ran some tests using the iOS simulator with the nuget package from your [link](https://ci.appveyor.com/project/CharliePoole/nunit-xamarin/build/3.0.1-ci-00132-update-libr/artifacts) and it worked fine.

Let me know if there's something specific you want me to test.

Options used on the test 
<img width="912" alt="test" src="https://cloud.githubusercontent.com/assets/5697434/23841967/fdefbdd0-07fc-11e7-9a13-f18b47ab5d29.png">

**Comment by ChrisMaddock** [comment]
@plneto - that's brilliant, thank you! I think your options look like they make a good smoke test.

Unfortunately, we don't yet have a proper test suite for this, so I think I smoke test is the best we can do. My concern really was that some of the library updates, or changes to the framework could have had some caused some weirdness. If there's nothing obviously apparent, I'd say we're good to go!

We're hoping to get 3.6 out this week. 😄

**Comment by ChrisMaddock** [comment]
@joaoasilva @plneto - v 3.6.1 is now live, thanks for the extra prompt! 😄

**Comment by joaoasilva** [comment]
Thanks! Will try it as soon as I can get my hands on it!
