### ISSUE TITLE
Start time, End time, and Duration not displayed.  Xaml bindings need to be updated.

### ISSUE THREAD

**Issue by jalbertSyncroTech** [nunit/nunit.xamarin#97]
In src/runner/nunit.runner/View/SummaryView.xaml, the bindings for Start time, End time, and Duration need to be updated.

The message during runtime is
Binding: 'TestResult' property not found on 'NUnit.Runner.Helpers.ResultSummary', target property: 'Xamarin.Forms.Label.Text'

This seems to have broken in commit ab94ca7e82627f1faed8b272343446673eb43a0c on Jan 6 when the ITestResult TestResult property was removed from src/runner/nunit.runner/Helpers/ResultSummary.cs

**Comment by ChrisMaddock** [comment]
Sorry about that. Thanks for reporting it.

**Comment by fcantagalli** [comment]
Hi @ChrisMaddock recently I found the same bug.
Any updates about It?

**Comment by ChrisMaddock** [comment]
Sorry @fcantagalli - it's one thing on a long list of things I want to sort out eventually.

We'd love a pull request to fix it, if you'd be willing? 😄

**Comment by felipetozato** [comment]
Sorry to not answer before @ChrisMaddock. Super busy month at work plus university.
I will take a look at this bug and open an PR as soon as I have something.

**Comment by fcantagalli** [comment]
Sorry to not answer before @ChrisMaddock. Super busy month at work plus university.
I will take a look at this bug and open an PR as soon as I have something.

**Comment by ChrisMaddock** [comment]
Great - thanks @fcantagalli!

**Comment by mikkelbu** [comment]
@ChrisMaddock looks like this was solved by #115.

**Comment by ChrisMaddock** [comment]
It does - thanks!
