### ISSUE TITLE
error CS0619: 'TestFixtureAttribute' is obsolete

### ISSUE THREAD

**Issue by danielc103** [nunit/nunit.xamarin#99]
Testing same project on two differnt Mac OS environments. Both on same versions of mono and msbuild.  One builds with no error, the other throws error

```
Test.cs(5,6): error CS0619: 'TestFixtureAttribute' is obsolete: 'The NUnit framework shipped with Mono is deprecated and will be removed in a future release. It was based on NUnit 2.4 which is long outdated. Please move to the NUnit NuGet package or some other form of acquiring NUnit.'
```

msbuild /version
```
Microsoft (R) Build Engine version 15.2.0.0 (xplat-2017-02/c2edfeb Thu May 18 13:58:03 EDT 2017)
Copyright (C) Microsoft Corporation. All rights reserved.
```

Mono -V
```
Mono JIT compiler version 5.0.1.1 (2017-02/5077205 Thu May 18 16:11:37 EDT 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  x86
	Disabled:      none
	Misc:          softdebug 
	LLVM:          yes(3.6.0svn-mono-master/8b1520c)
	GC:            sgen (concurrent by default)
```

Initial setup, no extra code, just empty project.
```
using NUnit.Framework;
using System;
namespace DukeProviders.UnitTests
{
    [TestFixture()]
    public class Test
    {
        [Test()]
        public void TestCase()
        {
        }
    }
}

```

Tried uninstalling and reinstalling NUnit nuget package 2.6.4 and also updating to 3.7.1. When building with xbuild, same failure with `Task "Csc" execution -- FAILED`. Any suggestions?

**Comment by CharliePoole** [comment]
TestFixtureAttribute is not obsolete in any version of NUnit that we produce or produced in the past. Therefore, that message resulted from some other piece of software that defines TestFixtureAttribute and marks it as obsolete. Possibly from a modified version of NUnit.

Please indicate what references are used in your project to help us figure this out.

**Comment by danielc103** [comment]
References
`System 4.0.0.0 .NET Framework 4.6.1`
From packages
`nunit.framework.dll 2.6.4.14350`

**Comment by CharliePoole** [comment]
Hmmm... Bit of a mystery. How did you install NUnit - i.e. what package did you use?

**Comment by danielc103** [comment]
Fixed.  When copied project to the second machine it wouldn't work, even after updating Nuget package. Would remove and add 2.6.4 back still got error. Finally removed and downgraded to 2.6.3, it worked. Upgraded to 3.7.1, still worked. 

Command line - ran `nuget restore project.sln` before running msbuild - worked. 

Not sure why full restore needed and Xamarin IDE restore didn't work.  Also not sure why UITest project using same NUnit package never threw error on either machine.
